UUWebstore/Controllers/websettingController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UUWebstore.Models;
using UUWebstore.Models.BaseClass;
using UUWebstore.Models.IRepositories;
using UUWebstore.Models.Repositories;

namespace UUWebstore.Controllers
{
    public class websettingController : BaseClass
    {
        private readonly IsettingServices _IsettingServices;
        public websettingController()
        {
            _IsettingServices = new settingServices();
        }
        public ActionResult availablebanners()
        {
            ViewBag.userId = new SelectList(_IsettingServices.bannersCreaTedBy().Select(e => new { e.userId, e.fullName }), "userId", "fullName");
            return View();
        }

        public ActionResult uploadbanner()
        {
            return View();
        }
        [HttpPost]
        public ActionResult uploadbanner(banner obanner, HttpPostedFileBase file)
        {                      
            if (file != null)
            {
                obanner.bannerImgURL= UploadFile(file, "/bannersImg");             
            }
            else {
                TempData["result"] = "Please upload banner image";
                return View();
            }
          
            if (_IsettingServices.uploadBanner(obanner) == 1)
            {
                TempData["result"] = "Banner uploaded. ";
                return RedirectToAction("availablebanners");
            }           
            return View();
        }
        public ActionResult Partial_SearchBannerReult(int userId)
        {            
            var result = _IsettingServices.bannersCreaTedByUserId(userId);
            return PartialView("Partial_SearchUsersReult", result);
        }
        public ActionResult Edit(int id)
        {          
            return View(_IsettingServices.getBannerById(id));
        }
        [HttpPost]
        public ActionResult Edit(banner obanner, HttpPostedFileBase file)
        {        
            if (file != null)
            {
                obanner.bannerImgURL = UploadFile(file, "/bannersImg");
            }
            else
            {
                TempData["result"] = "Please upload banner image";
                return View(obanner);
            }
            if (_IsettingServices.uploadBanner(obanner) == 1)
            {
                TempData["result"] = "Banner updated. ";               
            }          
            return View(obanner);
        }

        public ActionResult AllProductCategories()
        {
            return View();
        }
        public ActionResult Partial_SearchProductCategorieReult(int ddl_filter)
        {         
            return PartialView("Partial_SearchProductCategorieReult", _IsettingServices.GetAllProductCategories(ddl_filter));
        }
        public int makeFeaturedCategory(bool chk, int productCategoryId, Int64 proCategoryClientId)
        {
            return  chk ==true? _IsettingServices.MakeProductCategoriesAsFeatured(productCategoryId) : _IsettingServices.RemoveProductCategoriesAsFeatured(productCategoryId);
                 
        }

        [HttpGet]
        public ActionResult promotionalVideo()
        {
            ViewBag.Video = _IsettingServices.GetVideo();
            return View();
        }
        [HttpPost]       
        public ActionResult promotionalVideo(FormCollection frm)
        {
            string Video = frm["Pramotinal_Video_Url"].ToString();
            ViewBag.message= _IsettingServices.UpdateVideo(Video)==1?"Record updated.":"Record not updated.";
            ViewBag.Video = frm["Pramotinal_Video_Url"].ToString();
            return View();
        }
        [HttpGet]
        public ActionResult PromotionalBlock()
        {
            var promotionalBlockClass = new promotionalBlockClass();
            promotionalBlockClass.promotionalBlock = _IsettingServices.GetBlock();
            return View(promotionalBlockClass);
        }
        [HttpPost]
        public ActionResult PromotionalBlock(promotionalBlockClass opromotionalBlockClass)
        {
            ViewBag.message=_IsettingServices.UpdateBlock(opromotionalBlockClass.promotionalBlock) == 1 ? "Record updated." : "Record not updated.";
            return View(opromotionalBlockClass);
        }
    }
}

UUWebstore/Views/websetting/AllProductCategories.cshtml
@using UUWebstore.Models;
<h2>All Product Categories</h2>
@{
    Layout = "~/Views/Shared/_LayoutInternal.cshtml";
}
    <div class="form-horizontal">
 
       

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="row">
            <div class="col-md-3">
                <div class="form-group">
                  <select id="ddl_filter">
                      <option value="0">All</option>
                      <option value="1">Featured</option>
                  </select>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <input type="button" value="Search" class="btn btn-default" onclick="searchResult()" />

                </div>
            </div>
        </div>*@
      
    </div>

    <div class="table-responsive col-lg-12" id="viewResult">
        <div class="col-lg-12 white-box">
            <p>Please wait..</p>
        </div>
    </div>



<script>
    $(document).ready(function () {
        searchResult()
    })
   
</script>
<script>

    function searchResult() {

        //var ddl_filter = $("#ddl_filter").val();
        var ddl_filter =0;
        debugger
        $.ajax({
            url: '@BaseUtil.GetApplicationPath()' + '/websetting/Partial_SearchProductCategorieReult',
            type: 'POST',
            data: {'ddl_filter': ddl_filter },
            success: function (data) {
                $('#viewResult').html(data);
            },
            error: function () {
                bootbox.alert({
                    title: "Alert !",
                    message: '<p>Whooaaa! Something went wrong..</p>',
                    timeOut: 2000

                });

            }
        });
    }
</script>
<script>

    $(document).ready(function () {
        debugger
        if ('@TempData["result"] ' != null && '@TempData["result"] ' != '') {
                bootbox.alert({
                    title: "Success !",
                    message: '<p>' + TempData["result"] + '</p>',
                });
        }
    });
</script>

UUWebstore/Views/websetting/Edit.cshtml
@model UUWebstore.Models.banner

@{
    Layout = "~/Views/Shared/_LayoutInternal.cshtml";
}

@using (Html.BeginForm("Edit", "websetting", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>banner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.bannerId)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.srNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.srNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.srNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">

                <div class="col-md-9 choose-img">
                    <img id="pic" src='@Model.bannerImgURL' alt="Logo" width="300px" height="200px">
                    <input type="file" id="photoA" name="file" class="choose-input">
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isActive)
                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
      
        @Html.HiddenFor(model => model.bannerImgURL)
 
                @Html.HiddenFor(model => model.createdBy)
                @Html.HiddenFor(model => model.createdDate)      
                 @Html.HiddenFor(model => model.isDelete)

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "availablebanners")
</div>
<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            //Get reference of FileUpload.
            var fileUpload = document.getElementById("photoA");
            if (fileUpload.value.length > 0) {
                //Check whether the file is valid Image.
                var regex = new RegExp("([a-zA-Z0-9\s_\\.\-:])+(.jpg|.png|.gif)$");
                if (regex.test(fileUpload.value.toLowerCase())) {
                    var reader = new FileReader();
                    var s = fileUpload.files[0];
                    reader.readAsDataURL(s);
                    reader.onload = function (e) {
                        var image = new Image();
                        image.src = e.target.result;
                        image.onload = function () {

                            var height = this.height;
                            var width = this.width;
                            if (height > 200 || width > 200) {


                                bootbox.alert({
                                    title: "Alert !",
                                    message: 'Height and Width must not exceed 200px.'
                                });
                                return false;
                            }
                            else {

                                var reader1 = new FileReader();

                                reader1.onload = function (e) {
                                    $('#pic').attr('src', e.target.result);
                                }

                                reader1.readAsDataURL(input.files[0]);
                            }
                        };
                    }
                }
                else {

                    bootbox.alert({
                        title: "Alert !",
                        message: 'Please select .jpg,.png,.gif'
                    });
                    return false;
                }
            }

        }
    }

    $("#photoA").change(function () {
        readURL(this);
    });
</script>


<script>

    $(document).ready(function () {
        debugger
        if ('@TempData["result"]' != null && '@TempData["result"]' != '') {           
                bootbox.alert({
                    title: "Alert !",
                    message: '<p>'+@TempData["result"]+'</p>',
                    timeOut: 2000
                });           
        }
    });
</script>

UUWebstore/Views/websetting/Partial_SearchProductCategorieReult.cshtml
@model IEnumerable<UUWebstore.Models.getAllProductCategories_sp_Result>
<link href="~/Content/slimtable.css" rel="stylesheet" />
<script src="~/Scripts/slimtable.js"></script>
<table class="table" id="tblData">
    <thead>
        <tr>
            <th>Sr</th>
            <th>
               Category
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.createdByName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.modifiedByName)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.isActive)
            </th>
           
        </tr>
    </thead>
    @{
        var a = Model.Count();

    }
    <tbody>
        @if (a == 0)
        {
            <tr>
                <td colspan="3">
                    No Result Found
                </td>
            </tr>
        }
        @{  int i = 0; }
        @foreach (var item in Model)
        {

            <tr>
                <td>@(i += 1)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.createdByName)<br />@Html.DisplayFor(modelItem => item.createdDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.modifiedByName)<br />@Html.DisplayFor(modelItem => item.modifiedDate)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.isActive)
                </td>

                @*<td>
                    <input type="checkbox" id='chk_@item.productCategoryId' onclick="makeFeaturedCategory(@item.productCategoryId,@item.proCategoryClientId)" @(Convert.ToBoolean(@item.isFeaturedCategory) == true ? "checked='checked'" : string.Empty) />

                </td>*@
            </tr>
        }
    </tbody>
</table>
<script>
    function makeFeaturedCategory(id, proCategoryClientId)
    {
        var checkbox = document.getElementById('chk_' + id);
        var chk=false;
        if (checkbox.checked) {
            chk = true
        }
        debugger
        $.ajax({
            url: '/websetting/makeFeaturedCategory',
            type: 'POST',
            data: { 'chk': chk, 'productCategoryId': id, 'proCategoryClientId': proCategoryClientId },
            success: function (data) {
                if (data == 1)
                {
                    bootbox.alert({
                        title: "Success !",
                        message: '<p>Product featured category updated.</p>',
                        timeOut: 2000

                    });
                }
            },
            error: function () {
                bootbox.alert({
                    title: "Alert !",
                    message: '<p>Whooaaa! Something went wrong..</p>',
                    timeOut: 2000

                });

            }
        });

    }
</script>
<script>
    $(function () {
        $("#tblData").slimtable({
            tableData: null,
            dataUrl: null,
            itemsPerPage: 100,
            ipp_list: [10, 50, 100],
            colSettings: [],
            text1: "items/page",
            text2: "Loading...",
            sortStartCB: null,
            sortEndCB: null,
            aoColumnDefs: [{
                'bSortable': false,
                'aTargets': [-1] /* 1st one, start by the right */
            }]
        });
    });
</script>

UUWebstore/Views/websetting/Partial_SearchUsersReult.cshtml
@model IEnumerable<UUWebstore.Models.getAllbannersCreatedBy_sp_Result>

<table class="table" id="tblData">
    <thead>
        <tr>
            <th>Sr</th>
            <th>
              Banner Name
            </th>
            <th>
              Banner 
            </th>
            <th>
              Create By
            </th>

           
            <th>
                @Html.DisplayNameFor(model => model.isActive)
            </th>
            <th>Action</th>
        </tr>
    </thead> 

@{
    var a = Model.Count();

}
    <tbody>
        @if (a == 0)
        {
            <tr>
                <td colspan="6">
                    No Result Found
                </td>
            </tr>
        }



        @{    int i = 0; }
        @foreach (var item in Model)
        {
            <tr><td>@(i += 1)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    <a href="#"> <img src='@item.bannerImgURL' alt='@item.name' height="100" width="100" onclick="openModel('@item.bannerImgURL')" /></a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fullName)
                </td>

               
                <td>
                    @Html.DisplayFor(modelItem => item.isActive)
                </td>
                <td>
                    <a href="@Url.Action("Edit", "websetting", new { id = item.bannerId })"><i class="glyphicon glyphicon-pencil"></i></a>
                    <a onclick="RemoveRecord('productCatalog',@item.bannerId)"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="modal fade" tabindex="-1" id="loginModal"
     data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    ×
                </button>
                <h4 class="modal-title">Banner </h4>
            </div>
            <div class="modal-body">
               <img id="img" />
            </div>
        </div>
    </div>
</div>
<script>
    function openModel(bannerImgUR)
    {     debugger
        $('#img').attr('src', bannerImgUR);    
        $("#loginModal").modal('show');
    }
</script>

<script>
    $(function () {
        $("#tblData").slimtable({
            tableData: null,
            dataUrl: null,
            itemsPerPage: 100,
            ipp_list: [10, 50, 100],
            colSettings: [],
            text1: "items/page",
            text2: "Loading...",
            sortStartCB: null,
            sortEndCB: null,
            aoColumnDefs: [{
                'bSortable': false,
                'aTargets': [-1] /* 1st one, start by the right */
            }]
        });
    });
</script>

UUWebstore/Views/websetting/PromotionalBlock.cshtml
@model UUWebstore.Models.promotionalBlockClass

@{
    ViewBag.Title = "PromotionalBlock";
    Layout = "~/Views/Shared/_LayoutInternal.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Promotional Block</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class = "control-label col-md-2">promotional Block</label>   
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.promotionalBlock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.promotionalBlock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@{ var d = "";
    if (ViewBag.message != null)
    {
        d = ViewBag.message.ToString();
    }

}

<script>
    debugger
    if ('@d'!= '')
    {
        bootbox.alert({
            title: "Confirmation !",
            message: '@d'
        });
    }
</script>

UUWebstore/Views/websetting/availablebanners.cshtml
@using UUWebstore.Models;
@{
    Layout = "~/Views/Shared/_LayoutInternal.cshtml";
}
<div>
    @Html.ActionLink("Upload Banner", "uploadbanner")
</div>
<h2>Available Banners</h2>
<div class="row">
    <div class="form-group">    
        <div class="col-md-10">
            @Html.DropDownList("userId", null,"Created By", new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
          <div class="col-md-10">
            <input type="button" value="Search" class="btn btn-default" onclick="searchResult()" />
        </div>
    </div>
</div>
<div class="row">
    <div class="table-responsive" id="viewResult">
        <div class="col-lg-12 white-box">
            <p>Please use above search criteria to view the result list</p>
        </div>
    </div>
</div>
    <script>

        function searchResult() {
            debugger
            var userId = $("#userId").val();
            $.ajax({
                url: '@BaseUtil.GetApplicationPath()' + '/websetting/Partial_SearchBannerReult',
                type: 'POST',
                data: { 'userId': userId },
                success: function (data) {
                    debugger
                    $('#viewResult').html(data);
                },
                error: function () {
                    bootbox.alert({
                        title: "Alert !",
                        message: '<p>Whooaaa! Something went wrong..</p>',
                        timeOut: 2000

                    });

                }
            });
        }
    </script>

    <script>
    $(document).ready(function () {
        debugger
        if ('@TempData["result"]' != null && '@TempData["result"]' != '') {
                bootbox.alert({
                    title: "Success !",
                    message: '<p>Banner uploaded successfully</p>',
                });
        }
    });
    </script>

UUWebstore/Views/websetting/promotionalVideo.cshtml
@{
    ViewBag.Title = "promotionalVideo";
    Layout = "~/Views/Shared/_LayoutInternal.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>promotionalVideo</h2>
        <hr />
        <input type="text" name="Pramotinal_Video_Url" value="@ViewBag.Video" placeholder="Pramotinal Video Url" />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>

}


@{ var d = "";
    if (ViewBag.message != null)
    {
        d = ViewBag.message.ToString();
    }

}

<script>
    debugger
    if ('@d'!= '')
    {
        bootbox.alert({
            title: "Confirmation !",
            message: '@d'
        });
    }
</script>

UUWebstore/Views/websetting/uploadbanner.cshtml
@model UUWebstore.Models.banner
@{
    Layout = "~/Views/Shared/_LayoutInternal.cshtml";
}

@using (Html.BeginForm("uploadbanner", "websetting", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    <div class="form-horizontal">
        <h4>Upload Banner</h4>
      
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
           Name
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            Sr Number
            <div class="col-md-10">
                @Html.EditorFor(model => model.srNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.srNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-12"><label>Note: Try to upload banner of size 1920x570 </label></div>
        <div class="col-md-12">
            <div class="form-group">

                <div class="col-md-9 choose-img">
                    <img id="pic" src='@ViewBag.img' alt="Logo" width="600px" height="400px">
                    <input type="file" id="photoA" name="file" class="choose-input">
                </div>
            </div>
        </div>
       

        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isActive)
                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "availablebanners")
</div>
<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            //Get reference of FileUpload.
            var fileUpload = document.getElementById("photoA");
            if (fileUpload.value.length > 0) {
                //Check whether the file is valid Image.
                var regex = new RegExp("([a-zA-Z0-9\s_\\.\-:])+(.jpg|.png|.gif)$");
                if (regex.test(fileUpload.value.toLowerCase())) {
                    var reader = new FileReader();
                    var s = fileUpload.files[0];
                    reader.readAsDataURL(s);
                    reader.onload = function (e) {
                        var image = new Image();
                        image.src = e.target.result;
                        image.onload = function () {

                            var height = this.height;
                            var width = this.width;
                            if (height != 1920 || width != 570) {
                                bootbox.alert({
                                    title: "Alert !",
                                    message: 'Try to upload banner of size 1920x570'
                                });
                                return false;
                            }
                            else {

                                var reader1 = new FileReader();

                                reader1.onload = function (e) {
                                    $('#pic').attr('src', e.target.result);
                                }

                                reader1.readAsDataURL(input.files[0]);
                            }
                        };
                    }
                }
                else {

                    bootbox.alert({
                        title: "Alert !",
                        message: 'Please select .jpg,.png,.gif'
                    });
                    return false;
                }
            }

        }
    }

    $("#photoA").change(function () {
        readURL(this);
    });
</script>


<script>

    $(document).ready(function () {
        debugger
        if ('@TempData["result"]' != null && '@TempData["result"]' != '') {          
           
                bootbox.alert({
                    title: "Alert !",
                    message: '<p>'+@TempData["result"]+'</p>',
                    timeOut: 2000
                });          
        }
    });
</script>