UUWebstore/Models/user.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UUWebstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long userId { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string fullName { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string emailAddress { get; set; }
        public string website { get; set; }
        public string address { get; set; }
        public string location { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<int> stateId { get; set; }
        public Nullable<int> countryId { get; set; }
        public string zipcode { get; set; }
        public int roleID { get; set; }
        public string otp { get; set; }
        public long createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public bool isActive { get; set; }
        public bool isDelete { get; set; }
        public bool isBlocked { get; set; }
        public Nullable<System.DateTime> lastLogin { get; set; }
        public Nullable<System.DateTime> LastbadAttempt { get; set; }
        public Nullable<int> fakeAttemptCount { get; set; }
        public string supplier_PPAI_ASI { get; set; }
    }
}

UUWebstore/Controllers/usersController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using UUWebstore.Models;
using UUWebstore.Models.BaseClass;
using UUWebstore.Models.IRepositories;
using UUWebstore.Models.Repositories;

namespace UUWebstore.Controllers
{
    public class usersController : BaseClass
    {
        private readonly IRoleUserServices _IRoleUserServicess;
        private readonly IaccountServices _IAccountServices;
        private readonly IStateServices _IStateServices;
        private readonly ICountryServices _ICountryServices;
        public usersController()
        {
            _IAccountServices = new accountServices();
             _IRoleUserServicess = new RoleUserSerives();
            _IStateServices = new StateServices();
            _ICountryServices = new CountryServices();
        }

        // GET: users
        public ActionResult Index()
        {
            return View();
        }
        private void _fillDropDownList(user ouser=null)
        {
            if (ouser == null)
            {
                ViewBag.roleID = _IRoleUserServicess.getAllRoles().Select(e => new { e.roleID, e.name });
                ViewBag.countryId = _ICountryServices.getAllCountries().Select(e => new { e.countryId, e.name });
                ViewBag.stateId = _IStateServices.getAllStatesByCountryId(1).Select(e => new { e.stateId, e.name });
                ViewBag.cityId = _IStateServices.getAllCityByStateId(1).Select(e => new { e.cityId, e.CityName });
            }
            else {
                ViewBag.roleID = new SelectList(_IRoleUserServicess.getAllRoles().Select(e => new { e.roleID, e.name }), "roleID", "name", ouser.roleID);
                ViewBag.countryId = new SelectList(_ICountryServices.getAllCountries().Select(e => new { e.countryId, e.name }), "countryId", "name", ouser.countryId);
                ViewBag.stateId = new SelectList(_IStateServices.getAllStatesByCountryId(0).Select(e => new { e.stateId, e.name }), "stateId", "name", ouser.stateId);
                ViewBag.cityId = new SelectList(_IStateServices.getAllCityByStateId(0).Select(e => new { e.cityId, e.CityName }), "cityId", "CityName", ouser.cityId);
            }
        }
        public ActionResult Add_user()
        {
            _fillDropDownList();
            return View();
        }
        public ActionResult fillState(Int32 countryID)
        {
            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            string result = javaScriptSerializer.Serialize(_IStateServices.getAllStatesByCountryId(countryID).Select(e => new { e.stateId, e.name }));
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult fillCity(Int32 stateId)
        {
            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            string result = javaScriptSerializer.Serialize(_IStateServices.getAllCityByStateId(stateId).Select(e => new { e.cityId, e.CityName }));
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public ActionResult Add_user(UUWebstore.Models.user objUser)
        {
            bool result = false;
            _fillDropDownList();
            if (!_IAccountServices.boolCheckExiststance(objUser.userName, "uname"))
            {
                ViewBag.message = "User name already exists in database.";
            }
            else if (!_IAccountServices.boolCheckExiststance(objUser.mobile, "mobile"))
            {
                ViewBag.message = "Mobile number already exists in database.";
            }
            else if (!_IAccountServices.boolCheckExiststance(objUser.emailAddress, "email"))
            {
                ViewBag.message = "Email address already exists in database.";
            }
            else
            {
                result = _IAccountServices.create_update_userINformations_sp(objUser);
                TempData["result"] = "Record saved.";
                return RedirectToAction("searchUser");
            }
            TempData["result"] = "Record not saved.";
            return View(objUser);
        }
      
        public ActionResult Edit(Int64 userID)
        {
            ModelState.Remove("userName");
            ModelState.Remove("mobile");
            ModelState.Remove("emailAddress");
            var user = _IAccountServices.getUserById(userID);
            _fillDropDownList(user);
            return View(user);
        }
        [HttpPost]
        public ActionResult Edit(user user)
        {
            _fillDropDownList(user);
            bool result = _IAccountServices.create_update_userINformations_sp(user);
            ViewBag.message= result==true ? "Record saved.":  "Record not saved.";
            return View(user);
        }
        public JsonResult IsUserExists(string userName,string PreviousUsername)
        {
            return Json(userName == PreviousUsername ? true: _IAccountServices.boolCheckExiststance(userName, "uname"), JsonRequestBehavior.AllowGet);                      
        }
        public ActionResult IsMobileExists(string mobile,string Previousmobile)
        {
            return Json(mobile == Previousmobile ? true : _IAccountServices.boolCheckExiststance(mobile, "mobile"), JsonRequestBehavior.AllowGet);            
        }
        public ActionResult IsEmailExists(string emailAddress, string PreviousemailAddress)
        {
            return Json(emailAddress == PreviousemailAddress ? true : _IAccountServices.boolCheckExiststance(emailAddress, "email"), JsonRequestBehavior.AllowGet);            
        }
        public ActionResult searchUser()
        {
            ViewBag.roleID = new SelectList(_IRoleUserServicess.getAllRoles().Select(e => new { e.roleID, e.name }), "roleID","name",2);
            ViewBag.countryId = new SelectList(_ICountryServices.getAllCountries().Select(e => new { e.countryId, e.name }), "countryId", "name");
            ViewBag.stateId = new SelectList(_IStateServices.getAllStatesByCountryId(1).Select(e => new { e.stateId, e.name }), "stateId", "name");
            ViewBag.cityId = new SelectList(_IStateServices.getAllCityByStateId(1).Select(e => new { e.cityId, e.CityName }),"cityId","CityName");
            return View();
        }
        public ActionResult Partial_SearchUsersReult(int roleID, string  countryId, string stateId, string cityId, string userName, string fullName, string zipcode)
        {
            search osearch = new search();
            osearch.roleID = roleID;
            osearch.countryId = countryId == "" ? 0 : Convert.ToInt32(countryId);
            osearch.stateId =  stateId==""?0:Convert.ToInt32(stateId);
            osearch.cityId = cityId == "" ? 0 : Convert.ToInt32(cityId);
            osearch.userName = userName;
            osearch.fullName = fullName;
            osearch.zipcode = zipcode;
            var result = _IAccountServices.getFilteredUsers(osearch);
            return PartialView("Partial_SearchUsersReult", result);
        }
    }
}

UUWebstore/Views/users/Add_user.cshtml
@model UUWebstore.Models.user

@{
    Layout = "~/Views/Shared/_LayoutInternal.cshtml";
}

@using (Html.BeginForm("Add_user","users")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4  class="page-header">Add User</h4>
      
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        
        <div class="form-group">
            @Html.LabelFor(model => model.roleID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.roleID, new SelectList(ViewBag.roleID, "roleID", "name"), " Role ", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.roleID, "", new { @class = "text-danger" })
            </div>
        </div>  
        <div class="form-group">
            @Html.LabelFor(model => model.fullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fullName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

      
        <div class="form-group">
            @Html.LabelFor(model => model.countryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.countryId, new SelectList(ViewBag.countryId, "countryId", "name"), " Country ", new { @class = "form-control", onChange = "fillState()" })
               
                @Html.ValidationMessageFor(model => model.countryId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.stateId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.stateId, new SelectList(ViewBag.stateId, "stateId", "name"), " State ", new { @class = "form-control", onChange = "fillCity()" })
                @Html.ValidationMessageFor(model => model.stateId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.cityId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.cityId, new SelectList(ViewBag.cityId, "cityId", "CityName"), " City ", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.cityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.zipcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zipcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.supplier_PPAI_ASI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.supplier_PPAI_ASI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.supplier_PPAI_ASI, "", new { @class = "text-danger" })
            </div>
        </div>
       
          
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "searchUser","users")
</div>
<script>

    $(document).ready(function () {
        debugger
        if ('@TempData["result"] ' != null && '@TempData["result"] ' != '') {
                bootbox.alert({
                    title: "Alert !",
                    message: '<p>' + TempData["result"] + '</p>',
                });
        }
    });
</script>

UUWebstore/Views/users/Edit.cshtml
@model UUWebstore.Models.user
@{
    Layout = "~/Views/Shared/_LayoutInternal.cshtml";
}


@using (Html.BeginForm("Edit", "users"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>user</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.userId)
        @Html.HiddenFor(model => model.createdBy)
        @Html.HiddenFor(model => model.createdDate)
        @Html.Hidden("PreviousUsername", Model.userName)
        @Html.Hidden("Previousmobile", Model.mobile)
        @Html.Hidden("PreviousemailAddress", Model.emailAddress)
        <div class="form-group">
            @Html.LabelFor(model => model.roleID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.DropDownList("roleID", null, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            @Html.LabelFor(model => model.fullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.countryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("countryID", null, new { @class = "form-control", onChange = "fillState()" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.stateId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("stateId", null, new { @class = "form-control", onChange = "fillCity()" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.cityId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">              
                @Html.DropDownList("cityId", null, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.zipcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zipcode, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isActive)
                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDelete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isDelete)
                    @Html.ValidationMessageFor(model => model.isDelete, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.supplier_PPAI_ASI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.supplier_PPAI_ASI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.supplier_PPAI_ASI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>

    $(document).ready(function () {
        debugger
        if ('@ViewBag.message' != null && '@ViewBag.message' != '') {
                bootbox.alert({
                    title: "Alert !",
                    message: '<p>' + ViewBag.message + '</p>',
                });
        }
    });
</script>

UUWebstore/Views/users/Partial_SearchUsersReult.cshtml
@model IEnumerable<UUWebstore.Models.getFilteredUsers_Result>


<table class="table" id="tblData">
    
    <thead>
        <tr>
            <th>Sr</th>
            <th>
                User Name
            </th>
            <th>
                Full Name
            </th>
            <th>
                Phone
            </th>
            <th>
                Email Address
            </th>
            <th>
                Website
            </th>
            <th>
                Address
            </th>
            <th>
                Active
            </th>

            <th>
                supplier PPAI/ASI
            </th>
            <th>
                Created By
            </th>
          

            <th></th>
        </tr>
    </thead>

    @{
        var a = Model.Count();

    }
    <tbody>
        @if (a == 0)
        {
            <tr>
                <td colspan="12">
                    No Result Found
                </td>
            </tr>
        }



        @{    int i = 0; }
        @foreach (var item in Model)
        {

            <tr>
                <td>@(i += 1)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.userName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.phone) <br />@Html.DisplayFor(modelItem => item.mobile)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.emailAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.website)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.address) ,@Html.DisplayFor(modelItem => item.location)<br />
                    @Html.DisplayFor(modelItem => item.cityName),@Html.DisplayFor(modelItem => item.stateName),@Html.DisplayFor(modelItem => item.countryName), @Html.DisplayFor(modelItem => item.zipcode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.isActive)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.supplier_PPAI_ASI)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.createdByName)<br />@item.createdDate.ToString("MM/dd/yyyy")
                </td>

                <td>
                    <a href="@Url.Action("Edit", "users", new { userID = item.userId })"><i class="glyphicon glyphicon-pencil"></i></a>
                    <a onclick="RemoveRecord('productCatalog',@item.userId)"><i class="glyphicon glyphicon-trash"></i></a>

                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(function () {
        $("#tblData").slimtable({
            tableData: null,
            dataUrl: null,
            itemsPerPage: 100,
            ipp_list: [10, 50, 100],
            colSettings: [],
            text1: "items/page",
            text2: "Loading...",
            sortStartCB: null,
            sortEndCB: null,
            aoColumnDefs: [{
                'bSortable': false,
                'aTargets': [-1] /* 1st one, start by the right */
            }]
        });
    });
</script>

UUWebstore/Views/users/searchUser.cshtml
@using UUWebstore.Models;
@*<link href="~/Content/slimtable.css" rel="stylesheet" />
<script src="~/Scripts/slimtable.js"></script>*@
@{
    Layout = "~/Views/Shared/_LayoutInternal.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p>
            @Html.ActionLink("Create New", "Add_user","users")
        </p>
        <h4 class="page-header">search</h4>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    @Html.DropDownList("roleID", null, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    @Html.DropDownList("countryId", null, "Country", new { @class = "form-control", onChange = "fillState()" })

                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    @Html.DropDownList("stateId", null, "State", new { @class = "form-control", onChange = "fillCity()" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    @Html.DropDownList("cityId", null, "City", new { @class = "form-control" })

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <input class="form-control" type="text" id="txtuserName" placeholder="User Name" />

                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <input class="form-control" type="text" id="txtfullName" placeholder="Full Name" />

                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <input class="form-control" type="text" id="txtzipcode" placeholder="Zip Code" />
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <input type="button" value="Search" class="btn btn-default" onclick="searchResult()" />

                </div>
            </div>
        </div>
    </div>

    <div class="table-responsive col-lg-12" id="viewResult">
        <div class="col-lg-12 white-box">
            <p>Please use above search criteria to view the result list</p>
        </div>
    </div>


}

<script>

    function searchResult() {

        var roleID = $("#roleID").val();
        var countryId = $("#countryId").val();
        var stateId = $("#stateId").val();
        var cityId = $("#cityId").val();
        var txtuserName = $("#txtuserName").val();
        var txtfullName = $("#txtfullName").val();
        var txtzipcode = $("#txtzipcode").val();
        var p= '@BaseUtil.GetApplicationPath()'
        debugger
        $.ajax({
            url: p +'/users/Partial_SearchUsersReult',
            type: 'POST',
            data: {
                'roleID': roleID, 'countryId': countryId, 'stateId': stateId, 'cityId': cityId,
                'userName': txtuserName, 'fullName': txtfullName, 'zipcode': txtzipcode
            },
            success: function (data) {
                $('#viewResult').html(data);
            },
            error: function () {
                bootbox.alert({
                    title: "Alert !",
                    message: '<p>Whooaaa! Something went wrong..</p>',
                    timeOut: 2000

                });

            }
        });
    }
</script>
<script>

    $(document).ready(function () {
        debugger
        if ('@TempData["result"] ' != null && '@TempData["result"] ' != '') {
                bootbox.alert({
                    title: "Success !",
                    message: '<p>' + TempData["result"] + '</p>',
                });
        }
    });
</script>